### PR TITLE
Node bridge memory cleanup

### LINKED ISSUE #128: [graph-sdk] Use JS finalizer registration to handle freeing graph state
Initial attempt was unsuccessful; do a little more research & testing to try and use the JS finalizer mechanism to auto-free unused graph state.

### PR DESCRIPTION
**Pull request by aramikm**
# Goal
The goal of this PR is to implement an automated memory cleanup mechanism that might help free the memory in cases that the uses forget to manually free it.

Closes #128

### CODE REVIEW

**Review by JoeCap08055 — COMMENTED** [review]
Looks good--have you done any testing to see if the finalizer actually does anything?

**Comment by aramikm** [comment]
I've done testing but was not able to trigger that. It seems like it's not easy triggering it in Node. If you have any ideas how we might be able to force it to trigger I'm open to ideas.

**Comment by saraswatpuneet** [comment]
I was not able to reproduce it either , it has weird behavior and unpredictable it will be worth running a load test and let it wait to see if it ever gets triggered

**Comment by aramikm** [comment]
@JoeCap08055 @saraswatpuneet I was able to verify it by directly calling `global.gc` inside an app which triggers cleanup.
Running following code with following command
```bash
node --expose-gc dist/index.js
```

```ts
function interactWithGraph() {
    const environment: EnvironmentInterface =  {environmentType: EnvironmentType.Mainnet};
    for(let i=0;i<10; i++) {
        const graph= new Graph(environment);

        let public_follow_graph_schema_id = graph.getSchemaIdFromConfig(environment, ConnectionType.Follow, PrivacyType.Public);

        let connect_action: ConnectAction = {
            type: "Connect",
            ownerDsnpUserId: "1",
            connection: {
                dsnpUserId: "2",
                schemaId: public_follow_graph_schema_id,
            } as Connection,
            dsnpKeys: {
                dsnpUserId: "2",
                keysHash: 100,
                keys: [],
            } as DsnpKeys,
        } as ConnectAction;

        let actions = [] as Action[];
        actions.push(connect_action);

        let applied = graph.applyActions(actions);
        console.log(applied);

        let connections_including_pending = graph.getConnectionsForUserGraph("1", public_follow_graph_schema_id, true);
        console.log(connections_including_pending);

        let exported = graph.exportUpdates();
        console.log(exported);
    }
    if (global.gc) {
        global.gc();
    } else {
        console.log('Garbage collection unavailable.  Pass --expose-gc '
            + 'when launching node to enable forced garbage collection.');
    }
}
```

which printed
```
freeing 8
freeing 7
freeing 6
freeing 5
freeing 4
freeing 3
freeing 2
freeing 1
freeing 0
```

**Comment by saraswatpuneet** [comment]
Thats a cool thing to know 🥇

**Review by saraswatpuneet — APPROVED** [review]
👍🏽

**Pull request merged**
