### PR TITLE
SDK docs for ffi

### PR DESCRIPTION
**Pull request by saraswatpuneet**
# Goal
The goal of this PR is 

part of: #79

### CODE REVIEW

**Comment by saraswatpuneet** [comment]
Changes specific to this PR are as follows

https://github.com/LibertyDSNP/graph-sdk/pull/101/commits/71864db4a5830579231be90b37a41eb1e34dff9c

**Comment by saraswatpuneet** [comment]
image

**Comment by saraswatpuneet** [comment]
Add documentation for JNI too

image

**Review by aramikm — APPROVED** [review]
LGTM!

**Pull request merged**
